package com.tysonista.tizencommitlog;

import jenkins.model.Jenkins;
import net.sf.json.JSONObject;

import org.kohsuke.stapler.DataBoundConstructor;
import org.kohsuke.stapler.QueryParameter;
import org.kohsuke.stapler.StaplerRequest;

import hudson.Extension;
import hudson.model.Hudson;
import hudson.model.ParameterValue;
import hudson.model.ParameterDefinition;
import hudson.model.ParametersDefinitionProperty;
import hudson.model.ParameterDefinition.ParameterDescriptor;
import hudson.util.FormValidation;

public class TizenGitParameterDefinition extends ParameterDefinition {

    @DataBoundConstructor
    public TizenGitParameterDefinition(String name) {
        super(name);
    }

    public String getRootUrl() {
        return Jenkins.getInstance().getRootUrl();
    }

    /**
     * Execute the script and return the default value for this parameter.
     * @return the default value generated by the script or {@code null}
     */
    public final String getDefaultValue()
    {
      return "kakakakakak";
    }

    /**
     * 
     */
    private static final long serialVersionUID = -730014143015177976L;

    @Override
    public ParameterValue createValue(StaplerRequest arg0) {
        // TODO Auto-generated method stub
        return null;
    }

    @Override
    public ParameterValue createValue(StaplerRequest arg0, JSONObject arg1) {
        // TODO Auto-generated method stub
        return null;
    }

    @Extension
    public static class DescriptorImpl extends ParameterDescriptor {
        @Override
        public String getDisplayName() {
            return "Tizen Commit Logs";
        }
        public FormValidation doTest() {
            return FormValidation.ok("button clicked.");
        }
    }
}
